version: '1.0'
name: comax-mcp

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

deploy:
  strategy: rolling
  replicas: 1
  update_config:
    order: start-first
    failure_action: rollback
    delay: 10s
  rollback_config:
    failure_action: pause
    max_failure_ratio: 0
    monitor: 5m
    order: stop-first
    parallelism: 1

monitoring:
  endpoints:
    - path: /health
      interval: 30s
      timeout: 5s 